### ISSUE TITLE
Is there an option to change port?

### ISSUE THREAD

**Issue by Shaunieboy** [jusdepatate/webra1n-as-a-service#1]
I have my website on port 80 so I can't access it :P

**Comment by bc1bb** [comment]
It was meant to be run on checkra1n-only devices, anyways I will drop a release where we will be able to choose ports tomorrow

**Comment by bc1bb** [comment]
I'm still working on it as I'm bad at C, you could this use simple workaround;
- change [this line](https://github.com/jusdepatate/webra1n-as-a-service/blob/master/webra1nlauncher/webra1nlauncher.c#L9)
- `bash MAIN.sh uninstall`
- `bash MAIN.sh install`

**Comment by Shaunieboy** [comment]
yeah, I did that shortly after posting the question. Seems to work fine for me. Good work :)

**Comment by bc1bb** [comment]
i'm working on a much better solution, reopened and I will close when it'll be out
